SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO R 
WHERE FAVORITES = (
    SELECT MAX(R2.FAVORITES)
    FROM REST_INFO R2
    WHERE R.FOOD_TYPE = R2.FOOD_TYPE
    GROUP BY R2.FOOD_TYPE
)
ORDER BY FOOD_TYPE DESC