-- [MySQL]
-- SELECT DATETIME AS 시간
-- FROM ANIMAL_INS
-- ORDER BY DATETIME ASC
-- LIMIT 0, 1;

-- ORACLE
SELECT * FROM (
    SELECT DATETIME AS 시간
    FROM ANIMAL_INS
    ORDER BY DATETIME ASC
) WHERE ROWNUM = 1