SELECT T.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_TREE T
INNER JOIN ITEM_INFO I ON I.ITEM_ID = T.ITEM_ID
INNER JOIN ITEM_INFO P ON T.PARENT_ITEM_ID = P.ITEM_ID
WHERE P.RARITY = 'RARE'
ORDER BY T.ITEM_ID DESC;